// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-kPd72QZ56kM--H_6UBybFoA1t-OvR1A',
    appId: '1:803179839740:web:4f8bdbd4c805d920d11779',
    messagingSenderId: '803179839740',
    projectId: 'mybudgetdiary-d4972',
    authDomain: 'mybudgetdiary-d4972.firebaseapp.com',
    databaseURL: 'https://mybudgetdiary-d4972-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybudgetdiary-d4972.appspot.com',
    measurementId: 'G-GPXSGCV8HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzD1dPYKxVWKXgWgJF1ip8YRO7y0lfCMs',
    appId: '1:803179839740:android:8d85cacea3988104d11779',
    messagingSenderId: '803179839740',
    projectId: 'mybudgetdiary-d4972',
    databaseURL: 'https://mybudgetdiary-d4972-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybudgetdiary-d4972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrDrzmIViFi5ZWMpMmSPMhlz4hDxHuZwY',
    appId: '1:803179839740:ios:7a12cf197b62dcaed11779',
    messagingSenderId: '803179839740',
    projectId: 'mybudgetdiary-d4972',
    databaseURL: 'https://mybudgetdiary-d4972-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybudgetdiary-d4972.appspot.com',
    iosClientId: '803179839740-ebcbgba5dfhle96ojln2cq3snteiua6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybudgetdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrDrzmIViFi5ZWMpMmSPMhlz4hDxHuZwY',
    appId: '1:803179839740:ios:23f95e701905a810d11779',
    messagingSenderId: '803179839740',
    projectId: 'mybudgetdiary-d4972',
    databaseURL: 'https://mybudgetdiary-d4972-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybudgetdiary-d4972.appspot.com',
    iosClientId: '803179839740-icq1hacfu40nbaluujbvq1vfuorb70k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybudgetdiary.RunnerTests',
  );
}
